package pl.edu.agh.colonialskirmish.game;

public enum CardType {
	NONE,

	/* Main categories */
	SHIP, GROUND_UNIT, PLANET, ACTION, UPGRADE,

	/* Secondary categories */
	SHIP_COMMAND_SHIP, SHIP_SUPPORT, SHIP_FIGHTER, SHIP_BATTLE_SHIP, SHIP_SPECIAL, GROUND_INFANTRY, GROUND_VEHICLE, UPGRADE_PLANET_UPGRADE, UPGRADE_UNIT_UPGRADE

}
